modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="grp" #mandatory
version="${file.jarVersion}" #mandatory
displayName="GalacticRP Mod" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="jowashere" #optional
description='''
Mod for galactic rp.
'''
[[dependencies.grp]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.grp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
